#!/usr/bin/env node
// Regenerate lib/capybara/simulated/js/src/css-property-data.js from mdn-data (the
// property database css-tree already vendors). Emits NAMES ONLY — the longhand set and
// each shorthand's sub-longhands — which the CSSOM `all`-shorthand model and generic
// shorthand serialization need. mdn-data ships transitively via css-tree, so regenerate
// when css-tree (or its bundled mdn-data) is bumped:
//   pnpm run gen:css-property-data      (== node script/gen_css_property_data.js)
//
// mdn-data marks a shorthand by giving `computed` an ARRAY of longhand names; a longhand's
// `computed` is a string. Vendor-prefixed (`-…`) and custom (`--…`) properties are dropped.

const fs = require('fs');
const path = require('path');

const mdnPath = require.resolve('mdn-data/css/properties.json', { paths: [require.resolve('css-tree')] });
const props = JSON.parse(fs.readFileSync(mdnPath, 'utf8'));

const longhands = [];
const shorthands = {};
for (const name of Object.keys(props).sort()) {
  if (name.startsWith('-')) continue;                 // vendor-prefixed / custom
  const computed = props[name].computed;
  if (Array.isArray(computed)) shorthands[name] = computed.filter((c) => !c.startsWith('-'));
  else longhands.push(name);
}

const out =
`// GENERATED by script/gen_css_property_data.js from mdn-data — DO NOT EDIT BY HAND.
// Names only (no syntax/values): the longhand set + each shorthand's sub-longhands, used
// by the CSSOM \`all\`-shorthand model and generic css-wide shorthand serialization.

// Every standard longhand property (a property whose value is a single field, not a
// shorthand). \`all\` resets all of these except \`direction\` and \`unicode-bidi\`.
export const LONGHANDS = new Set(${JSON.stringify(longhands)});

// Each standard shorthand → the longhand properties it sets, per mdn-data.
export const SHORTHAND_LONGHANDS = ${JSON.stringify(shorthands, null, 0)};
`;

const dest = path.join(__dirname, '..', 'lib', 'capybara', 'simulated', 'js', 'src', 'css-property-data.js');
fs.writeFileSync(dest, out);
console.log(`wrote ${dest}: ${longhands.length} longhands, ${Object.keys(shorthands).length} shorthands`);
