# frozen_string_literal: true

# Generates ext/csim_native/src/unicode.rs — the code-point ranges of the Unicode general categories the
# native engine has to agree with the oracle about: MARKS (`\p{M}`), which `font::zero_width` needs to decide
# whether a character at or above U+0300 is zero-width, and LETTERS / NUMBERS (`\p{L}` / `\p{N}`), which
# `layout::hyphen_breaks_after` needs because the oracle's `HYPHEN_BREAK_RE` spells its classes that way.
#
# The ORACLE asks these regexes, so the authority is the JS ENGINE the oracle runs in, not Ruby and not Rust
# std — their Unicode versions differ, and they move independently. Measured: Ruby 17.0.0 called 8 ranges
# marks that this V8 does not (a driver page then measured a character 8px wider in one engine than the
# other), and rustc's `char::is_alphabetic` knows 4662 code points this V8 does not (a hyphen then broke a
# line in native that the oracle kept whole). So the tables are enumerated by asking the driver's own engine —
# and `spec/native_layout_text_spec.rb` re-enumerates them through `ranges_of` below and compares the WHOLE
# range list, so an upgrade of any of the three reds the suite instead of drifting silently.
#
#   bundle exec ruby script/gen_unicode_classes.rb
require 'capybara/simulated'
require 'rack'

module UnicodeClasses
  OUT = File.expand_path('../ext/csim_native/src/unicode.rs', __dir__)

  # The tables, and what each one is for. `from` truncates a table where the CALLER decides the answer
  # itself: `font::zero_width` handles every code point below U+0300 from structure, so the marks below it
  # would be dead weight.
  CLASSES = [
    {const: 'COMBINING_MARKS', klass: 'M', from: 0x300, fn: 'is_combining_mark', what: 'a combining mark'},
    {const: 'LETTERS',         klass: 'L', from: 0,     fn: 'is_letter',         what: 'a letter'},
    {const: 'NUMBERS',         klass: 'N', from: 0,     fn: 'is_number',         what: 'a number'}
  ].freeze

  # Every range of `\p{klass}` at or above `from`, asked of the session's own engine. ONE crossing walks the
  # whole code space in ~0.02s, so neither this nor its caller has any reason to sample or to batch.
  def self.ranges_of(session, klass, from)
    session.evaluate_script(<<~JS)
      (() => {
        const RE = new RegExp('^' + String.fromCharCode(92) + 'p{#{klass}}$', 'u');  // a literal escape would be eaten by the heredoc
        const out = [];
        let start = null;
        for (let cp = #{from}; cp <= 0x10FFFF; cp++) {
          const hit = cp >= 0xD800 && cp <= 0xDFFF ? false : RE.test(String.fromCodePoint(cp));
          if (hit) { if (start === null) start = cp; }
          else if (start !== null) { out.push([start, cp - 1]); start = null; }
        }
        if (start !== null) out.push([start, 0x10FFFF]);
        return out;
      })()
    JS
  end

  def self.blank_session
    Capybara::Session.new(:simulated, Rack::Builder.new {
      run ->(_env) { [200, {'content-type' => 'text/html; charset=utf-8'}, ['<!doctype html><html><body></body></html>']] }
    }.to_app).tap {|s| s.visit '/' }
  end
end

if $PROGRAM_NAME == __FILE__
  session = UnicodeClasses.blank_session
  tables  = UnicodeClasses::CLASSES.map {|c| c.merge(ranges: UnicodeClasses.ranges_of(session, c[:klass], c[:from])) }
  engine  = session.driver.js_engine   # the engine that ANSWERED, auto-detect included — not what the env asked for

  body = tables.map {|t|
    rows  = t[:ranges].map {|lo, hi| format('    (0x%04X, 0x%04X),', lo, hi) }.join("\n")
    scope = t[:from].zero? ? '' : format(' at or above U+%04X (below that `font::zero_width` decides for itself)', t[:from])
    <<~RUST
      // The code points of `\\p{#{t[:klass]}}`#{scope}.
      const #{t[:const]}: &[(u32, u32)] = &[
      #{rows}
      ];

      // Whether `cp` is #{t[:what]}. Binary search over #{t[:ranges].size} disjoint, ascending ranges —
      // which they are because `ranges_of` builds them that way, and native_layout_text_spec compares the
      // whole list back against it.
      pub(crate) fn #{t[:fn]}(cp: u32) -> bool {
          in_ranges(#{t[:const]}, cp)
      }
    RUST
  }.join("\n")

  File.write(UnicodeClasses::OUT, <<~RUST)
    // GENERATED by script/gen_unicode_classes.rb — do not edit. Source: the driver's own JS engine
    // (#{engine}), because the oracle asks these same regexes there and parity is against that answer — not
    // against Ruby's Unicode tables, and not against Rust std's (all three disagree, and their versions move
    // independently).
    //
    // `\\p{M}` is the one question `font::zero_width` cannot answer from structure: at or above U+0300 a
    // character is zero-width exactly when it is a mark. Without it every CJK run, em space, dash and emoji
    // reached an undecidable arm and took the whole layout pass down with it. `\\p{L}` and `\\p{N}` are the
    // classes the oracle's `HYPHEN_BREAK_RE` is written in, which decide where a hyphen offers a line break.

    #{body.strip}

    fn in_ranges(table: &[(u32, u32)], cp: u32) -> bool {
        table
            .binary_search_by(|&(lo, hi)| if cp < lo { std::cmp::Ordering::Greater } else if cp > hi { std::cmp::Ordering::Less } else { std::cmp::Ordering::Equal })
            .is_ok()
    }
  RUST
  puts "#{tables.map {|t| "#{t[:const]} #{t[:ranges].size}" }.join(', ')} from #{engine} → #{UnicodeClasses::OUT}"
end
