# frozen_string_literal: true

# Generates ext/csim_native/src/combining.rs — the code-point ranges of Unicode COMBINING MARKS
# (`\p{M}`), which `font::zero_width` needs to answer the one question it could not decide on its
# own: a character at or above U+0300 is zero-width exactly when it is a mark.
#
# The ORACLE asks `/^\p{M}$/u`, so the authority is the JS ENGINE the oracle runs in, not Ruby —
# their Unicode versions differ (measured: Ruby 17.0.0 called 8 ranges marks that this V8 does not,
# and a driver page then measured a character 8px wider in one engine than the other). So the table
# is enumerated by asking the driver's own engine, and `spec/native_layout_text_spec.rb` re-asks it
# at every range boundary so a Ruby or V8 upgrade reds the suite instead of drifting silently.
#
#   bundle exec ruby script/gen_combining_marks.rb
require 'capybara/simulated'
require 'rack'

OUT = File.expand_path('../ext/csim_native/src/combining.rs', __dir__)

session = Capybara::Session.new(:simulated, Rack::Builder.new {
  run ->(_env) { [200, {'content-type' => 'text/html'}, ['<!doctype html><html><body></body></html>']] }
}.to_app)
session.visit '/'

# One crossing per 4096-code-point block, each answering with the ranges it found — a million
# per-character crossings would take minutes.
ranges = []
(0x300..0x10FFFF).step(0x1000) do |base|
  found = session.evaluate_script(<<~JS)
    (() => {
      const MARK_RE = new RegExp('^' + String.fromCharCode(92) + 'p{M}$', 'u');  // the heredoc would eat a literal escape
      const out = [];
      let start = null;
      for (let cp = #{base}; cp < #{[base + 0x1000, 0x110000].min}; cp++) {
        const mark = cp >= 0xD800 && cp <= 0xDFFF ? false : MARK_RE.test(String.fromCodePoint(cp));
        if (mark) { if (start === null) start = cp; }
        else if (start !== null) { out.push([start, cp - 1]); start = null; }
      }
      if (start !== null) out.push([start, #{[base + 0x1000, 0x110000].min - 1}]);
      return out;
    })()
  JS
  found.each do |lo, hi|
    if ranges.last && ranges.last[1] == lo - 1 then ranges.last[1] = hi   # a range split across two blocks
    else ranges << [lo, hi]
    end
  end
end

engine = session.driver.js_engine   # the engine that ANSWERED, auto-detect included — not what the env asked for
rows = ranges.map {|lo, hi| format('    (0x%04X, 0x%04X),', lo, hi) }.join("\n")
File.write(OUT, <<~RUST)
  // GENERATED by script/gen_combining_marks.rb — do not edit. Source: the driver's own JS engine
  // (#{engine}), because the oracle asks the same `\\p{M}` regex there and parity is against that answer, not
  // against Ruby's Unicode tables (they disagree; the two versions move independently).
  //
  // The code-point ranges of Unicode COMBINING MARKS, which is the one question `font::zero_width`
  // cannot answer from structure: at or above U+0300 a character is zero-width exactly when it is a
  // mark. Without this every CJK run, em space, dash and emoji reached an undecidable arm and took
  // the whole layout pass down with it.

  pub(crate) const COMBINING_MARKS: &[(u32, u32)] = &[
  #{rows}
  ];

  // Whether `cp` is a combining mark. Binary search over #{ranges.size} ranges, asked once per
  // non-ASCII character of a run.
  pub(crate) fn is_combining_mark(cp: u32) -> bool {
      COMBINING_MARKS
          .binary_search_by(|&(lo, hi)| if cp < lo { std::cmp::Ordering::Greater } else if cp > hi { std::cmp::Ordering::Less } else { std::cmp::Ordering::Equal })
          .is_ok()
  }
RUST
puts "#{ranges.size} ranges from #{engine} → #{OUT}"
