#!/usr/bin/env node
// Regenerate lib/capybara/simulated/js/src/css-property-data.js from mdn-data (the
// property database css-tree already vendors). Emits NAMES ONLY — the longhand set and
// each shorthand's sub-longhands — which the CSSOM `all`-shorthand model and generic
// shorthand serialization need. mdn-data ships transitively via css-tree, so regenerate
// when css-tree (or its bundled mdn-data) is bumped:
//   pnpm run gen:css-property-data      (== node script/gen_css_property_data.js)
//
// mdn-data marks a shorthand by giving `computed` an ARRAY of longhand names; a longhand's
// `computed` is a string. Vendor-prefixed (`-…`) and custom (`--…`) properties are dropped.

const fs = require('fs');
const path = require('path');

const mdnPath = require.resolve('mdn-data/css/properties.json', { paths: [require.resolve('css-tree')] });
const props = JSON.parse(fs.readFileSync(mdnPath, 'utf8'));

const longhands = [];
const shorthands = {};
for (const name of Object.keys(props).sort()) {
  if (name.startsWith('-')) continue;                 // vendor-prefixed / custom
  const computed = props[name].computed;
  if (Array.isArray(computed)) shorthands[name] = computed.filter((c) => !c.startsWith('-'));
  else longhands.push(name);
}

// Valid pseudo-class / pseudo-element base names (leading `:`/`::` and any `()` stripped),
// for validating a `selectorText` setter — an unknown pseudo makes the selector invalid.
const selPath = require.resolve('mdn-data/css/selectors.json', { paths: [require.resolve('css-tree')] });
const selectors = JSON.parse(fs.readFileSync(selPath, 'utf8'));
const pseudos = new Set();
for (const key of Object.keys(selectors)) {
  const m = /^::?([a-z-]+)/i.exec(key);               // ':active', '::before', ':has()' → base name
  if (m) pseudos.add(m[1].toLowerCase());
}

const out =
`// GENERATED by script/gen_css_property_data.js from mdn-data — DO NOT EDIT BY HAND.
// Names only (no syntax/values): the longhand set, each shorthand's sub-longhands, and the
// valid pseudo-class/element base names — used by the CSSOM \`all\`-shorthand model, generic
// css-wide shorthand serialization, and \`selectorText\` pseudo validation.

// Every standard longhand property (a property whose value is a single field, not a
// shorthand). \`all\` resets all of these except \`direction\` and \`unicode-bidi\`.
export const LONGHANDS = new Set(${JSON.stringify(longhands)});

// Each standard shorthand → the longhand properties it sets, per mdn-data.
export const SHORTHAND_LONGHANDS = ${JSON.stringify(shorthands, null, 0)};

// Valid pseudo-class / pseudo-element base names (a \`selectorText\` with an unknown pseudo is
// invalid). Vendor-prefixed (\`-webkit-…\`) pseudos are accepted separately (forward-compat).
export const PSEUDO_NAMES = new Set(${JSON.stringify([...pseudos].sort())});
`;

const dest = path.join(__dirname, '..', 'lib', 'capybara', 'simulated', 'js', 'src', 'css-property-data.js');
fs.writeFileSync(dest, out);
console.log(`wrote ${dest}: ${longhands.length} longhands, ${Object.keys(shorthands).length} shorthands`);
