# frozen_string_literal: true

# Writes lib/capybara/simulated/js/src/css-properties.js: the properties a page can name, as the style engine has them
# (cssom_decl.rs `properties`). A realm's CSSOM interfaces are built from it where no engine is attached yet (the
# snapshot), so the engine's list travels as data, and spec/css_properties_spec.rb holds the file to the engine. Run it
# after the engine's properties change, with the extension built, then rebuild the bridge:
#
#   bundle exec rake compile && bundle exec ruby script/gen_css_properties.rb && pnpm run build:bridge

require 'json'

module CssProperties
  FILE = File.expand_path('../lib/capybara/simulated/js/src/css-properties.js', __dir__)

  HEADER = <<~JS
    // GENERATED by script/gen_css_properties.rb from the style engine (cssom_decl.rs `properties`) — do not edit.
    //
    // Every property a page can name: `[name, property, animatable, longhands, initial]` — the property an alias names
    // (its own name otherwise), whether it animates, a shorthand's longhands in the engine's order, and a longhand's
    // initial value as a computed style serializes it.
  JS

  # The file's text for the engine's rows.
  def self.source(rows)
    "#{HEADER}export const PROPERTIES = [\n#{rows.map {|row| "  #{JSON.generate(row)}" }.join(",\n")}\n];\n"
  end

  # The engine's rows, asked of a page.
  def self.engine_rows
    require 'capybara/simulated'
    session = Capybara::Session.new(:simulated, ->(_env) { [200, {'content-type' => 'text/html'}, ['<!DOCTYPE html>']] })
    session.visit '/'
    session.evaluate_script('__dom.styleProperties()')
  ensure
    session&.quit
  end
end

File.write(CssProperties::FILE, CssProperties.source(CssProperties.engine_rows)) if $PROGRAM_NAME == __FILE__
